/**
 * Canonical error codes returned in the API envelope.
 *
 * Kept as a const object (not a TS enum) so the runtime values are
 * plain strings and the wire contract is stable across builds.
 */

export const ErrorCode = {
  // Authentication / authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_OTP: 'AUTH_INVALID_OTP',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  AUTH_PHONE_IN_USE: 'AUTH_PHONE_IN_USE',
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  AUTH_INVALID_REFRESH: 'AUTH_INVALID_REFRESH',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Generic HTTP-shaped failures
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Domain-specific
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_INSUFFICIENT_FUNDS',
  POST_NOT_ELIGIBLE: 'POST_NOT_ELIGIBLE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',

  // Last resort
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorStatus: Record<ErrorCode, number> = {
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_INVALID_OTP: 400,
  AUTH_OTP_EXPIRED: 400,
  AUTH_OTP_RATE_LIMITED: 429,
  AUTH_PHONE_IN_USE: 409,
  AUTH_EMAIL_IN_USE: 409,
  AUTH_INVALID_REFRESH: 401,
  AUTH_UNAUTHORIZED: 401,
  AUTH_FORBIDDEN: 403,
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  WALLET_INSUFFICIENT_FUNDS: 400,
  POST_NOT_ELIGIBLE: 400,
  UPLOAD_TOO_LARGE: 413,
  UPLOAD_INVALID_TYPE: 415,
  INTERNAL_ERROR: 500,
};
